### ISSUE TITLE
Bad link to oaml repository (missing LoadTrackProgress)

### ISSUE THREAD

**Issue by vmoquay** [oamldev/oamlGodotModule#1]
Hello and thank you for this Godot module.
I would like to report following issue:
Link to oaml repository (@ 6e3081d) is not up-to-date to compile oamlGodotModule, indeed LoadTrackProgress function was introduce in commit 07a9724

Here is the error log:
_compiling oamlGodotModule.cpp (g++)
modules/oamlGodotModule/oamlGodotModule.cpp: In member function 'float oamlGodotModule::LoadTrackProgress(String)':
modules/oamlGodotModule/oamlGodotModule.cpp:117:20: error: 'class oamlApi' has no member named 'LoadTrackProgress'; did you mean 'LoadTrack'?_

Replacing oaml directory with oaml master (git clone https://github.com/oamldev/oaml.git) compile correctly

**Comment by marcelofg55** [comment]
Just fixed this, the link was outdated, thanks for reporting!
