### ISSUE TITLE
Godot 3.0 compatibility

### ISSUE THREAD

**Issue by arthurtemple** [oamldev/oamlGodotModule#2]
Hi,

Considering Godot 3.0 is now officially out, is there a reflection currently going on as to the fate of this module?

I am looking forward to see oaml support on latest Godot and could give it a go on my spare time, however with the massively breaking changes on Godot audio system I would be glad to get your insight as to what the general (re-)design should be.

Thanks a lot for your awesome work on oaml.

**Comment by marcelofg55** [comment]
Hi, thanks for your interest in oaml :).
Now that Godot 3.0 is out I will definitely update this to the support it. It shouldn't be to hard to update, I'll look into it tomorrow.

**Comment by marcelofg55** [comment]
Fixed in latest commit.

**Comment by arthurtemple** [comment]
That went fast!
Fantastic work, thanks a lot.
